items/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='items'
urlpatterns=[
    path('', views.view_items,  name='all'),
    path('item/<int:item_id>',  views.view_item, name='item'),
    path('add_item/',    views.add_item, name='add_item'),
    path('delete_item/<int:item_id>',    views.delete_item, name='delete_item'),
    path('update_item/<int:item_id>',    views.update_item, name='update_item'),
    path('description/<int:item_id>',   views.add_description,  name='description'),
    path('summary/<int:item_id>',   views.add_summary,  name='summary'),
    path('author/<int:author_id>',  views.view_author,  name='author'),
    path('authors/',    views.view_authors, name='authors'),
    path('add_author/', views.add_author,   name='add_author'),
    path('delete_author/<int:author_id>',  views.delete_author,    name='delete_author'),
    path('update_author/<int:author_id>',  views.update_author,    name='update_author')
]

knowbase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
]

items/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Item(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField(null=True)
    summary = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=100)
    items = models.ManyToManyField(Item, through="Author_Item")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Author_Item(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
                models.UniqueConstraint(fields=['author', 'item'], name="uniqueAuthorItem")
            ]


class Fragment(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Fragment_Item(models.Model):
    fragment = models.ForeignKey(Fragment, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    summary = models.TextField(null=True)
    done = models.BooleanField(null=True, default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
                models.UniqueConstraint(fields=['fragment', 'item'], name="uniqueFragmentItem")
            ]


class Game(Item):
    ganre = models.CharField(max_length=80)  # should be choices but tag based
    estimated_playing_time = models.IntegerField()


class Book(Item):
    ganre = models.CharField(max_length=80)  # should be choices but tag based
    pages = models.PositiveIntegerField(help_text='Enter number of pages', null=True)

items/forms.py
from django import forms
from items.models import Book, Item, Author


class ItemDescriptionForm(forms.Form):
    description = forms.CharField(label='description', widget=forms.Textarea)
    summary = forms.CharField(label='summary', widget=forms.Textarea)


class AuthorForm(forms.Form):
    name = forms.CharField(label='Author name')


class ItemForm(forms.Form):
    title = forms.CharField(label='Title')
    author = forms.CharField(label='Author')

items/views.py
from django.shortcuts import render, get_object_or_404

from django.db.models import QuerySet

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.conf import settings
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations
from items.models import Author, Book, Item, Fragment_Item, Fragment, Author_Item
from items.forms import ItemDescriptionForm, AuthorForm, ItemForm

class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)


def view_items(request):
    context = {}

    items = Item.objects.all()
    template = "items/items.html"
    context["items"] = items

    return render(request, template_name=template, context=context)


def view_item(request, item_id: int):
    context = {}
    template = "items/item.html"

    item = get_object_or_404(Item, pk=item_id)
    fragments = get_item_fragments(item_id)
    authors = get_authors_of_an_item(item_id)
    
    context["item"] = item
    context["fragments"] = fragments
    context["authors"] = authors

    return render(request, template_name=template, context=context)


#TODO: add methods to handle this mess. One to add item when author exists and another, when he exists
# and what if item exists? - Hmm There can be a book with title the same as the other. 
def add_item(request):
    template = "items/add_item.html"
    context = {}
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = Item(title=form.cleaned_data["title"])
            item.save()
            if author_exists(name=form.cleaned_data["author"]) is False:
                author = Author(name=form.cleaned_data["author"])
                author.save()
                author_item = Author_Item(author=author, item=item)
                author_item.save()
            else:
                author = Author.objects.filter(name=form.cleaned_data["author"]).get()
                author_item = Author_Item(author=author, item=item)
                author_item.save()
                context["form"] = form
                return render(request, template_name=template, context=context)



            return HttpResponseRedirect("/items/")
    else:
        form = ItemForm()
        context["form"] = form
        return render(request, template_name=template, context=context)


def author_exists(name: str) -> bool:
    if Author.objects.filter(name=name):
        return True
    
    return False


def delete_item(request, item_id: int):
    item = get_object_or_404(Item, pk=item_id)
    item.delete()

    return HttpResponseRedirect("/items/")


def update_item(request, item_id: int):
    template = "items/update_item.html"
    context = {}
    item = get_object_or_404(Item, pk=item_id)
    author = get_authors_of_an_item(item_id)
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item.title = form.cleaned_data["title"]
            item.save()
            return HttpResponseRedirect(f"/items/item/{item_id}")
    else:
        form = ItemForm()
        form.fields["title"].initial = item.title
        form.fields["author"].initial = author.first().name
        context["form"] = form
        context["item"] = item

        return render(request, template_name=template, context=context)


def view_authors(request):
    template = 'items/authors.html'
    authors_list = Author.objects.all() 
    context = {'authors_list': authors_list}

    return render(request, template_name=template, context=context)


def view_author(request, author_id: int):
    context = {}
    author = get_object_or_404(Author, pk=author_id)
    items = get_items_of_an_author(author_id)
    template = 'items/author.html'

    context = {'author': author, 'items': items}
    
    return render(request, template_name=template, context=context)


def add_author(request):
    template = "items/add_author.html"
    context = {}
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = Author(name=form.cleaned_data["name"])
            author.save()
            return HttpResponseRedirect("/items/authors/")
    else:
        form = AuthorForm()
        context["form"] = form
        return render(request, template_name=template, context=context)


def update_author(request, author_id: int):
    author = get_object_or_404(Author, pk=author_id)
    context = {}
    template = "items/update_author.html"

    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author.name = form.cleaned_data["name"]
            author.save()
            return HttpResponseRedirect(f"/items/author/{author_id}")

    if request.method == "GET":
        form = AuthorForm()
        form.fields["name"].initial = author.name
        context["form"] = form
        context["author"] = author
        return render(request, template_name=template, context=context)


def delete_author(request, author_id: int):
    author = get_object_or_404(Author, pk=author_id)
    author.delete()

    return HttpResponseRedirect("/items/authors/")


def get_book_fragments(book_id: int) -> QuerySet[Fragment]:
    return Fragment.objects.filter(fragment_item__item__id=book_id)


def get_item_fragments(item_id: int) -> QuerySet[Fragment]:
    return Fragment.objects.filter(fragment_item__item__id=item_id)


def get_items_of_an_author(author_id: int) -> QuerySet[Item]:
    return Item.objects.filter(author_item__author__id=author_id)


def get_authors_of_an_item(item_id: int) -> Author:
    try:
        return Author.objects.filter(author_item__item__id=item_id)
    except Author.DoesNotExist:
        return None


def add_description(request, item_id: int):
    item = Item.objects.get(pk=item_id)
    if request.method == "POST":
        form = ItemDescriptionForm(request.POST)
        if form.is_valid():
            item.description = form.cleaned_data["description"]
            item.summary = form.cleaned_data["summary"]
            item.save()
            return HttpResponseRedirect("/items/items/")

    else:
        form = ItemDescriptionForm()
        form.description = item.description
        form.summary = item.summary
        return render(request, "items/add_description.html", {"form": form})


def add_summary(request, item_id: int):
    item = Item.objects.get(pk=item_id)
    return HttpResponse(item.title)

items/templates/items/add_author.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Dodaj autora</h2>
  <p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:authors' %}';return false;">
  </form>
{% endblock %}:

items/templates/items/add_description.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:all' %}';return false;">
  </form>
</p>
{% endblock %}

items/templates/items/add_item.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Dodaj utwór</h2>
  <p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:all' %}';return false;">
  </form>
{% endblock %}:

items/templates/items/author.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h2>{{ author }}</h2>

  <ol>
  {% for item in items %}
  <li>
    <a href="{% url 'items:item' item.id %}">{{ item }}</a>
  </li>
  {% empty %}
  <li>brak utworów</li>
  {% endfor %}
  </ol>
  
  <p>
  <a href="{% url 'items:delete_author' author.id %}">Usuń Autora</a>
  </p>
  <p>
  <a href="{% url 'items:authors' %}">Autorzy</a>
  </p>
{% endblock %}

items/templates/items/authors.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h2>Autorzy</h2>
  <ol>
  {% for author in authors_list %}
  <li>
    <h4><a href="{% url 'items:author' author.id %}">{{ author }}</a></h4> -  
    <a href="{% url 'items:delete_author' author.id %}">Usuń</a> | 
    <a href="{% url 'items:update_author' author.id %}">Aktualizuj</a>
  </li>
  {% empty %}
  <h4>brak autorów</h4>
  {% endfor %}
  </ol>
  <h5><a href="{% url 'items:add_author' %}">Dodaj autora</a></h5>
{% endblock %}

items/templates/items/item.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h3>{{ item }}</h3>
  <ul>
      {% for fragment in fragments %}
      <li>
        {{ fragment }}
      </li>
      {% empty %}
      <p>no fragments, sir</p>
      {% endfor %}
  </ul>
  <p>
  {% if authors %}
    Autor{{ authors|pluralize:"zy" }}: 
    {% for author in authors %}
        <a href="{% url 'items:author' author.id %}">{{ author }}</a>  
    {% endfor %}
    | 
  {% endif %}
  <a href="{% url 'items:all' %}"> - Lista utworów</a>
  </p>
{% endblock %}

items/templates/items/items.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <div class="float-right"><h2>Utwory</h2><h3><a href="{% url 'items:add_item' %}">Dodaj utwór</a></h3>
    </div>
  <ol>
  {% for item in items %}
  <li>
    <h4><a href="{% url 'items:item' item.id %}">{{ item }}</a></h4>
    <a href="{% url 'items:delete_item' item.id %}">Usuń</a> | 
    <a href="{% url 'items:update_item' item.id %}">Aktualizuj</a>
  </li>
  {% empty %}
  <li>Brak utworów</li>
  {% endfor %}
  </ol>
{% endblock %}

items/templates/items/update_author.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Aktualizuj autora</h2>
  <p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:authors' %}';return false;">
  </form>
{% endblock %}:

items/templates/items/update_item.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h2>Aktualizuj Utwór</h2>
  <p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'items:item' item.id %}';return false;">
  </form>
{% endblock %}: